# Generated by Django 5.0.6 on 2024-06-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='profecion',
            new_name='profesion',
        ),
    ]
