# Generated by Django 5.0.6 on 2024-06-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_profecion_profesor_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
