# Generated by Django 5.0.6 on 2024-06-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_entregable_entregado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='mail',
            new_name='email',
        ),
    ]
